language: perl
perl:
  - "5.20"
  - "5.8"

matrix:
  include:
    - perl: "5.6"
      env: AUTHOR_TESTING=0 COVERAGE=0

env:
  global:
    - COVERAGE=1

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
